---
swagger: "2.0"
info:
  description: "Gestor de activos informáticos"
  version: "1.0.0"
  title: "Activos Informáticos Web Services"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /assets/types:
    get:
      tags:
      - "AssetType"
      summary: "Consulta de tipos de activos informáticos"
      description: "Listado de todos los tipos de activos informáticos disponibles"
      operationId: "assetTypeGet"
      parameters: []
      responses:
        200:
          description: "Listado de tipos de activos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AssetType"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "AssetType"
      summary: "Crear tipo de activo"
      description: "Dar de alta un nuevo tipo de activo informático"
      operationId: "assetTypePost"
      parameters:
      - in: "body"
        name: "assetType"
        description: "Tipo de activo informático a dar de alta en el sistema"
        required: true
        schema:
          $ref: "#/definitions/NewAssetType"
      responses:
        201:
          description: "Tipo de activo creado"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    x-swagger-router-controller: "AssetType"
  /users:
    get:
      tags:
      - "User"
      summary: "Consulta de usuarios"
      description: "Listado de todos los usuarios autorizados a utlizar el servicio"
      operationId: "usersGet"
      parameters: []
      responses:
        200:
          description: "Listado de usuarios"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "User"
      summary: "Crear usuario"
      description: "Dar de alta un usario dandole asi permiso para utlizar el servicio"
      operationId: "usersPost"
      parameters:
      - in: "body"
        name: "user"
        description: "Usuario a dar de alta en el sistema"
        required: true
        schema:
          $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "Usuario creado"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    x-swagger-router-controller: "User"
  /users/{id}:
    get:
      tags:
      - "User"
      summary: "Usuario"
      description: "Usuario por identificador\n"
      operationId: "usersIdGet"
      parameters:
      - name: "id"
        in: "path"
        description: "identificador del usuario."
        required: true
        type: "string"
      responses:
        200:
          description: "Usuario por id."
          schema:
            $ref: "#/definitions/User"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "User"
      summary: "Usuario"
      description: "Usuario por identificador\n"
      operationId: "usersIdPut"
      parameters:
      - name: "id"
        in: "path"
        description: "identificador del usuario."
        required: true
        type: "string"
      - in: "body"
        name: "user"
        description: "Datos de usuario para actualizar"
        required: true
        schema:
          $ref: "#/definitions/UpdateUser"
      responses:
        204:
          description: "Usuario actualizado."
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
      - "User"
      summary: "Usuario"
      description: "Usuario por identificador\n"
      operationId: "usersIdDelete"
      parameters:
      - name: "id"
        in: "path"
        description: "identificador del usuario."
        required: true
        type: "string"
      responses:
        200:
          description: "Usuario borrado."
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
    x-swagger-router-controller: "User"
definitions:
  Hypermedia:
    type: "object"
    properties:
      rel:
        type: "string"
        description: "Nombre del recurso con el que se relaciona"
      href:
        type: "string"
        description: "URL de referencia al recurso"
  User:
    type: "object"
    properties:
      id:
        type: "string"
        description: "identificador único del usuario."
      name:
        type: "string"
        description: "Nombre de usuario."
      comment:
        type: "string"
        description: "Comentario acerca del usuario."
      deleted:
        type: "boolean"
        description: "Indica si se trata de un usuario ya eliminado o no."
      links:
        type: "array"
        description: "Listado de vínculos a recursos"
        items:
          $ref: "#/definitions/Hypermedia"
  NewUser:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Nombre de usuario."
      comment:
        type: "string"
        description: "Comentario acerca del usuario."
  UpdateUser:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Nombre de usuario."
      comment:
        type: "string"
        description: "Comentario acerca del usuario."
      deleted:
        type: "boolean"
        description: "Indica si se trata de un usuario ya eliminado o no."
  AssetType:
    type: "object"
    properties:
      id:
        type: "string"
        description: "identificador único del tipo de activo."
      name:
        type: "string"
        description: "Nombre del tipo de activo."
      fields:
        type: "array"
        description: "Listado de atributos que definen al tipo de activo"
        items:
          $ref: "#/definitions/AssetType_fields"
  NewAssetType:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Nombre del tipo de activo."
      fields:
        type: "array"
        description: "Listado de atributos que definen al tipo de activo"
        items:
          $ref: "#/definitions/AssetType_fields"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
  AssetType_fields:
    properties:
      name:
        type: "string"
        description: "Nombre del atributo"
      type:
        type: "string"
        description: "Tipo de dato del atributo"
